### ISSUE TITLE
Making it easier to clear filters

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#113]
When I was working on the user guide, I realized that the "Clear all" button is very subtle and hard to notice, even though this is likely to be a popular option. Should the styling be more noticeable? Maybe black with white text? You could also shorten the "Close" button so the "Clear all" button could fit on the same line without being taller - there's plenty of extra Close button width.

Also - I'm wondering if we should have an option to clear all filters that's outside of the pop-up? It might easier for the user, but I don't want to clutter up the interface...

**Comment by kjacobsen16** [comment]
Extended the 'Clear All' button.  Can discuss options for a button outside the pop-up in the touch-base.

**Comment by kjacobsen16** [comment]
Options:
Black w/ white text (as you suggested):
![image](https://user-images.githubusercontent.com/35497731/36873283-a3938588-1d6d-11e8-81f3-949dd9f3e821.png)

slightly darker background color:
![image](https://user-images.githubusercontent.com/35497731/36873479-37772264-1d6e-11e8-9a46-e2920ee450b4.png)

same as project count box :
![image](https://user-images.githubusercontent.com/35497731/36873398-fe70c150-1d6d-11e8-8d57-2ee1041ec147.png)
--This one makes the most sense to me, since it matches the rest of the app, but I included the others just in case.

**Comment by jlbruce** [comment]
I agree, I like the last version with the darker gray.
