### ISSUE TITLE
Update User Guide - edits made

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/SiGL#118]
- [x] Image of filtered project - filter/all/site coloring

- [x] popup - overlapping sites

**Comment by jlbruce** [comment]
Some edits to the User Guide imagery (sorry for being so picky).

- [ ] Opening a site info box: This screenshot should really be retaken now that we've got the new highlight icon with the point in the center. Since this item is exactly about that - clicking on the site dot - we should show that.
- [ ] View overlapping sites: Will need to be retaken after the new pop-up styling is in place.
- [ ] Select overlapping sites: Same dot issue here - there's no site dot in the middle of the highlight. Also, it might be better to choose a location with more than 2 sites and not over water , so the Spiderfy is more noticeable. It's a little lost in this location since the green "2" is overwhelmed by the wetland icons and the basemap colors.

----

- [ ] Changing or adding layers: New image with one of them checked, so the user can see the action they can take?

----

- [ ] The Project List: Image should contain at least one project in the screenshot so the user can see where to expect the list to start. Also need to wait until the new project count styling is applied.
- [ ] View site parameters: Expand screenshot to include at least one Biological parameter (not just the heading)
- [ ] Filter sites: Screenshot should include the Parameters option expanded and some of the Biological options checked (but not the top, select-all Biological option).
- [ ] Filter projects: Screenshot should include one of the Duration options expanded and selected.
- [ ] NEW! Submit Filters or Search: I added this to the spreadsheet.
- [ ] Clear selected lilters: Need to retake after "Clear all" styling is applied.

----

- [ ] Site list options: Will need to retake after new toggle styling is applied.
- [ ] Highlighting filters sites/highlighting all sites: It's pretty hard to tell the difference in the example you used - we need one where the different is immediately and drastically noticeable. Let me know if you'd like me to help find one. Also, will need to wait for new toggle styling before retaking.
