### ISSUE TITLE
Pop-ups broken in production application

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGL#144]
User discovered application-breaking bug - pop-up is not firing. 

> I was doing some research for a 6-12th grade water quality monitoring program I lead called Flint River GREEN and came across your mapper while searching for water quality data in our area. I have included a snip of the area I am investigating (Flint, MI) below and wonder if you can help me troubleshoot. It appears that I am supposed to click on the data points to learn about the project associated with them, but when I try to click on a data point, no information box appears. Is there something I am missing by chance?

**Comment by esmyers** [comment]
changed to LAYER_OPTION_ALL instead of LAYER_OPTION_VISIBLE when setting up the on click identify task.  Thanks to a single post in a dark corner of some random forum.  Not sure why this works because the layer is displayed on the map.

URL to try it yourself.
https://gis.wim.usgs.gov/arcgis/rest/services/SIGL/SIGLMapper/MapServer/identify?geometry=%7B%22x%22%3A-9958463.282780621%2C%22y%22%3A6047741.181067562%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&geometryType=esriGeometryPoint&sr=102100&layers=all&layerDefs=&time=&layerTimeOptions=&tolerance=8&mapExtent=%7B%22xmin%22%3A-11215699.524014866%2C%22ymin%22%3A5450920.864217064%2C%22xmax%22%3A-6565882.219372259%2C%22ymax%22%3A7057932.946884182%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&imageDisplay=1918%2C1067%2C96&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&dynamicLayers=&returnZ=false&returnM=false&gdbVersion=&f=html
