### ISSUE TITLE
site highlighting back to one color

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#92]
Initial request: when site point is clicked, the project shows in the sidebar. When that project name is clicked, all sites are highlighted on map in orange. Make that green since the project is not showing based on a filter.

I'm changing my mind on this one. I think the green highlight should be viewed as the Filtered Projects sites that are showing on the map but are not part of the filter. The orange highlight is just a highlight. 
When you click on a point in the map, it is orange highlighted, not green. When you click on a site name in the sidebar, it shows as orange highlight, not green. The only time green highlighting is used is for when a user clicks a site name from the sidebar that is not part of the filtered sites or clicks the project name that is listed from a filter and that project list is showing all the sites (not just filtered result site points) on the map. The green is only used to show that those sites are not part of the filtered results. All other select/highlight is in orange. 

Based on this logic, I'm swayed towards keeping it as is. 
Thoughts? @jlbruce , @esmyers , @HansVraga

**Comment by jlbruce** [comment]
Don't forget that when you first click on the "all" toggle, the sites that aren't filtered results first display gray with no green highlight. It isn't until you click on the project name that they add the green highlight. I'm more confident with this solution, but I see another change that we need to make...

Green sites: selected project sites with no filter applied. This includes initial load selection (both by clicking on project name AND a single site), and the non-filtered sites after a filter is applied.

Orange sites: only used post-filter, and only for sites matching filter.

I'm about to change the color scheme, but if it helps, I'm going to make the text consistent too... the project names in the lower spanner window are going to be in "green" since they discuss the entire project, and the filtered site names will stay "orange".

Is that better?

**Comment by troddick** [comment]
need others to read through this and lets meet to discuss how much work would be needed to change this in the app. @esmyers @kjacobsen16 @HansVraga

**Comment by HansVraga** [comment]
We're going to simplify highlighting - if a site or sites have been selected, they will be the same color regardless of other activities like filtering, etc. Keep the orange.

**Comment by troddick** [comment]
Keeping gray dots as those that are showing on the map when user toggles 'Show All'.
